# Generated by Django 3.2 on 2021-04-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Employee',
        ),
    ]
