# Generated by Django 3.1.4 on 2021-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210417_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmanager',
            fields=[
                ('f_name', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fdate', models.CharField(max_length=50)),
                ('cno', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('n_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
