# Generated by Django 3.1.4 on 2021-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20210422_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('fdate', models.CharField(max_length=50)),
                ('cno', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('m_pass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='hr_login',
            old_name='eid',
            new_name='hrid',
        ),
    ]
