# Generated by Django 3.1.4 on 2021-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20210422_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=5)),
                ('e_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
