# Generated by Django 3.1.4 on 2021-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eleave',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
