# Generated by Django 3.1.4 on 2021-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0023_remove_eleave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('man_pass', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='M_login',
        ),
    ]
