# Generated by Django 3.1.4 on 2021-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_m_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemp',
            old_name='mid',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='addman',
            old_name='eid',
            new_name='mid',
        ),
    ]
