# Generated by Django 3.1.4 on 2021-04-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20210422_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_login',
            old_name='m_pass',
            new_name='man_pass',
        ),
    ]
