# Generated by Django 3.1.4 on 2021-04-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_auto_20210425_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewleave',
            old_name='edate',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='viewleave',
            name='ltype',
        ),
        migrations.RemoveField(
            model_name='viewleave',
            name='rsn',
        ),
        migrations.RemoveField(
            model_name='viewleave',
            name='sdate',
        ),
    ]
