# Generated by Django 3.1.4 on 2021-04-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0022_auto_20210429_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleave',
            name='status',
        ),
    ]
