# Generated by Django 3.1.4 on 2021-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0025_auto_20210501_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptreject1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=5)),
                ('sdate', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=15)),
                ('ltype', models.CharField(max_length=50)),
                ('rsn1', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=5)),
                ('sdate', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=15)),
                ('ltype', models.CharField(max_length=50)),
                ('rsn1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewleave1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
