# Generated by Django 3.1.4 on 2021-05-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0026_acceptreject1_mleave_status1_viewleave1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man_login',
        ),
    ]
