# Generated by Django 3.1.4 on 2021-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0028_man_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man_login',
        ),
    ]
