# Generated by Django 3.1.4 on 2021-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0030_man_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hr_login',
        ),
    ]
