# Generated by Django 3.1.4 on 2021-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0031_delete_hr_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('n_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
