# Generated by Django 3.1.4 on 2021-05-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0032_hr_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mleave',
        ),
    ]
