# Generated by Django 3.1.4 on 2021-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0033_delete_mleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=5)),
                ('f_name', models.CharField(max_length=5)),
                ('sdate', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=15)),
                ('ltype', models.CharField(max_length=50)),
                ('rsn1', models.CharField(max_length=100)),
            ],
        ),
    ]
