# Generated by Django 3.1.4 on 2021-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0036_remove_eleave_rsn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleave',
        ),
    ]
