# Generated by Django 3.1.4 on 2021-05-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0038_eleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='E_login',
        ),
        migrations.RemoveField(
            model_name='mleave',
            name='rsn1',
        ),
    ]
