# Generated by Django 3.1.4 on 2021-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0039_auto_20210502_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=5)),
                ('f_name', models.CharField(max_length=25)),
                ('e_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
