# Generated by Django 3.1.4 on 2021-05-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0040_e_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acceptreject',
        ),
        migrations.DeleteModel(
            name='Acceptreject1',
        ),
    ]
