# Generated by Django 3.1.4 on 2021-05-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0042_acceptreject_acceptreject1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Status1',
        ),
        migrations.DeleteModel(
            name='Viewdetails',
        ),
    ]
