# Generated by Django 3.1.4 on 2021-05-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0043_auto_20210502_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleave',
        ),
    ]
