# Generated by Django 3.1.4 on 2021-05-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0045_eleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleave',
        ),
    ]
