# Generated by Django 3.1.4 on 2021-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0046_delete_eleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=5)),
                ('f_name', models.CharField(max_length=50)),
                ('sdate', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=15)),
                ('ltype', models.CharField(max_length=50)),
                ('avleave', models.IntegerField(default=7)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
