# Generated by Django 3.1.4 on 2021-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0047_eleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleave',
            name='avleave',
        ),
        migrations.RemoveField(
            model_name='eleave',
            name='status',
        ),
    ]
